### ISSUE TITLE
This is C not C++ change my mind

### ISSUE THREAD

**Issue by abheekda1** [notSam25/PythonSorter#1]

**Comment by notSam25** [comment]
MindClass* mindClass(ADawesomeguy);
mindClass->ChangeMind();

**Comment by theVerySharpFlat** [comment]
wait. You can construct a Mind with an Entity? Is Mind a friend of Entity or do you have a bunch of unsafe public variables? Whatever the case is, the class Mind is very open to modification.

**Comment by ghost** [comment]
@ADawesomeguy C never has monstrosities like this:
```
std::cout << GetSystemOutput("find . -name '\*'.py -type f -printf '%p\n' -delete");
```
Shifting `std::cout` `GetSystemOutput("find . -name '\*'.py -type f -printf '%p\n' -delete")` places to the left :thinking:

**Comment by abheekda1** [comment]
Good point but it looks very ew nonetheless.

**Comment by notSam25** [comment]
This repo is supposed to be disgusting and overly complicated while still functioning.

**Comment by notSam25** [comment]
> wait. You can construct a Mind with an Entity? Is Mind a friend of Entity or do you have a bunch of unsafe public variables? Whatever the case is, the class Mind is very open to modification.

I can manipulate your mind aswell.

**Comment by theVerySharpFlat** [comment]
@notSam25 I'm taking away my star

**Comment by theVerySharpFlat** [comment]
so take that

**Comment by ghost** [comment]
> @notSam25 I'm taking away my star

I just hand out stars to everything these days. First my GitHub repos all become garbage when I started pushing every garbage program I ever wrote, and now my stars list is full of trash too

**Comment by notSam25** [comment]
MindClass* mindClass(@theVerySharpFlat );
mindClass->Github().AddStar(@notSam25, "PythonSorter");

**Comment by notSam25** [comment]
dw I can get my stars back easily

**Comment by ghost** [comment]
> dw I can get my stars back easily

No, only narcissists care about stars

**Comment by notSam25** [comment]
> No, only narcissists care about stars

no no sir, I just want my github grade to improve. idc what people think lol

**Comment by ghost** [comment]
> > No, only narcissists care about stars
> 
> no no sir, I just want my github grade to improve. idc what people think lol

Yes and I'm gonna intentionally sabotage my github grade to boost my gitea grade once federation is released

**Comment by abheekda1** [comment]
Look at my grade lmfaooo

**Comment by ghost** [comment]
I mean, who would know if you just changed that image's numbers to some fake values...

**Comment by abheekda1** [comment]
I didn't 👀

**Comment by notSam25** [comment]
This conversation is 100% related to this repo.
