### ISSUE TITLE
This repo

### ISSUE THREAD

**Issue by theVerySharpFlat** [notSam25/PythonSorter#5]

**Comment by theVerySharpFlat** [comment]
Perhaps we should delete the files? Maybe that will solve the issue.

**Comment by ghost** [comment]
> Perhaps we should delete the files? Maybe that will solve the issue.

:brain:

**Comment by ghost** [comment]
GitHub bad I can't react with a :brain:

Also why does GitHub do that weird emoji==image thing? We have UTF-8 folks, so use it instead of whatever that bizarre thing GitHub does. (I'm a Gitea developer now so I see flaws in GitHub everywhere I look)

**Comment by notSam25** [comment]
Uninstall GitHub. Fixed.

**Comment by ghost** [comment]
> Uninstall GitHub. Fixed.

Once Gitea federation is released, I'll finally be able to do this!
